version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: nuri3d_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-secure_password_2024}
      MONGO_INITDB_DATABASE: nuri_section_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - nuri3d_network

  # Backend FastAPI
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: nuri3d_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: mongodb://admin:password123@mongodb:27017/nuri_section_db?authSource=admin
      PYTHONPATH: /app
    depends_on:
      - mongodb
    networks:
      - nuri3d_network
    volumes:
      - ./backend:/app/backend
      - ./server.py:/app/server.py
      - ./requirements.txt:/app/requirements.txt

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nuri3d_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - nuri3d_network

volumes:
  mongodb_data:

networks:
  nuri3d_network:
    driver: bridge
